In [3]:
import numpy as np
A = np.array([[[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]], [[[1,2,3], [4,5,6]], [[7,8,9], [10,11,15]]]])
print(A)
print(A.reshape(12,2))

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 15]]]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 15]]


In [23]:
print(A.reshape(A.shape[0],-1))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 15]]


In [22]:
A.shape

(2, 2, 2, 3)

In [18]:
np.sqrt(np.sum(np.square(A[0] - A[1])))

3.0

In [46]:
A = np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])
B = np.array([[4,4,4,4], [1,3,24,7]])

(A**2).sum(axis = 1, keepdims=True)

array([[ 30],
       [174],
       [446]])

In [47]:

(B**2).sum(axis = 1, keepdims=True)

array([[ 64],
       [635]])

In [48]:
(A**2).sum(axis=1)

array([ 30, 174, 446])

In [49]:
2 * B.dot(A.T)

array([[ 80, 208, 336],
       [214, 494, 774]])

In [50]:

(B**2).sum(axis = 1, keepdims=True) + (A**2).sum(axis=1) - 2 * B.dot(A.T)

array([[ 14,  30, 174],
       [451, 315, 307]])

In [2]:
A.mean(axis = 1)

array([[[  4. ,   5. ,   6. ],
        [  7. ,   8. ,   9. ]],

       [[  4. ,   5. ,   6. ],
        [  7. ,   8. ,  10.5]]])

In [7]:
A[0][1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [6]:
np.resize(A[0][1], (A[0][1].shape[0], 1))

array([[7],
       [8]])

In [10]:
A[0][1].dot([1,2,3])


array([50, 68])

In [5]:
np.bincount?

In [6]:
A = np.array([1,2,3,4,5,6,4,1,1])
np.bincount(A)

array([0, 3, 1, 1, 2, 1, 1])

In [18]:
def square(n,m):
    return n**2 + m**2
a = [lambda n,m: n**2 + m**2]
for i in a:
    print(i(10,11))


221
